mylist = [15,12,4,2,4,9,31,7]
mylist.append(0)
print(mylist)
print ("length of the list is", len(mylist))
print("minimum is", min(mylist))
print("maximum is", max(mylist))
mylist.reverse()
print("reverse is", mylist)
mylist.sort()
print("sorted list looks like", mylist)
mylist.reverse()
print("after reverse sorting", mylist)
mylist.insert(2,10)
print("inseted 10 at 3rd place",mylist)
mylist.remove(0)
print("removed 0    ", mylist)
a= "and".join(str(mylist))
print(a)